version: '3.6'
services:
  ruby:
    image: ruby
    volumes:
      - ./book:/pinscape-build-guide/book:ro
      - ./Gemfile:/pinscape-build-guide/Gemfile:ro
      - ./Gemfile.lock:/pinscape-build-guide/Gemfile.lock
      - ./Makefile:/pinscape-build-guide/Makefile:ro
      - ./dist:/pinscape-build-guide/dist
      - ./.ruby-version:/pinscape-build-guide/.ruby-version:ro
    working_dir: /pinscape-build-guide
    stdin_open: true
    tty: true
  nginx:
    image: nginx
    volumes:
      - ./dist/html:/usr/share/nginx/html:ro
    ports:
      - "80:80"