= What is a pin cab?

I'm not sure who created the first virtual pinball cabinet, but the seed of the idea is pretty obvious in hindsight.

Someone must have been playing around with a pinball program on their desktop PC, and wondered what it would be like to turn the monitor sideways, to make the layout more like a real pinball table's proportions.

Then they thought to lay it down flat, so they could stand over it like a real pinball playfield.

And then what about switching to a big flat-panel TV that's the same overall size as a real pinball table?
The finishing touch was putting the big TV inside an old cabinet salvaged from a defunct real pinball, right where the playfield used to go, for the full life-sized experience.

At its most basic, that pretty much sums up a virtual pin cab.

You take a Windows PC, install Visual Pinball and/or other pinball simulator software, attach a TV in the 40" range as the primary monitor, and put the TV inside a pinball cabinet body where the playfield would normally go.

Put another TV in the backbox to display the backglass artwork.

Connect some speakers in the backbox to the PC sound card, and you have the full audio/visual simulation.

==  What makes this so special?

Okay, you're thinking, so a pin cab is just a desktop pinball player in the guise of a real machine.
Maybe that sounds _somewhat_ interesting: the idea of playing on a full-size playfield is pretty novel if you're used to playing pinball in a cramped little perspective window on a PC monitor.
But in the end, isn't it just the same game on a bigger screen?
Wouldn't the novelty wear off pretty quickly?

As they say in the infomercials, "but wait, there's more..."

*Real flipper buttons!* Once we have the displays in a proper cabinet arrangement, we can't just plop a boring old PC keyboard on top and go on batting the ball with the Shift keys like on the desktop.
It's a real pin cab, so it needs real flipper buttons.

Yes, you can connect the real buttons to the PC.
There's a special device called a key encoder that lets you do this.
Key encoders are fairly cheap and easy to set up (and the Pinscape Controller can handle this function, of course).
They trick Windows into thinking you're still just pressing regular keyboard keys, so you can go on using the same pinball software.

This makes a positively huge difference in playability.
If you've played any desktop pinball or tablet pinball, you probably already have a sense for how awkward the controls are; you've undoubtedly lost a good number of balls from having your fingers stray just a little off the keys at crucial moments.
Even so, it'll probably still be a revelation the first time you play virtual pinball with real flipper buttons.

You don't have to (and shouldn't) stop at flipper buttons, by the way.
You can hook up all the standard buttons - the Start button, Magna Save buttons, the coin chutes, even the service buttons inside the coin door that let you access the operator menus.

*A real plunger!* Desktop pinball games all use a "timed" plunger that pulls back as long as you're pressing a key.
Which obviously doesn't even remotely resemble how you interact with the plunger on a real machine.
On a cabinet, you can install an actual pinball plunger, and connect it to a sensor that lets the PC read its position.
This lets you launch a ball exactly like in a real game.
The Pinscape Controller offers this capability, and several commercial options are available as well.

*Real nudging!* Real pinball games are physical, mechanical systems.
The game action obeys the laws of physics, not the whims of a video game programmer.
I think that's why pinball remains interesting to so many people even in an age of impossibly sophisticated video games.
Pinball's physicality means you can interact with the game in a very direct and visceral way.

Desktop pinball offers an imitation of nudging that's half-hearted at best, letting you "nudge" by pressing a button.
Like the timed plunger, it's nice that they tried, but it's nothing like the real thing.

A pin cab makes it possible to bring back real physical interaction.
A virtual cab already has the same heft and feel of a real cab, so you'll find yourself unconsciously nudging it like the real thing, your brain expecting it to influence the ball.
But what if you really could influence the ball that way?
Good news: you can! There's a device called an accelerometer that can measure exactly the sort of motion you impart to the cabinet by nudging.
Accelerometers are cheap and ubiquitous these days, thanks to smart phones.
The microcontroller board used in the Pinscape Controller has an accelerometer built in, and the Pinscape software is set up to read the acceleration data and send it to the pinball simulator program.
Most of the available commercial plunger kits offer the same capability.
The accelerometer doesn't just sense the fact that you nudged, but actually measures the amount of force you applied, and passes that along to the simulator, so that the response in the simulation is proportional to the strength of the physical nudge.

*Mechanical feedback! Blinking lights!* Once the early cabinet builders mastered all the above, they started coming up with ways to make the experience even more realistic by adding mechanical feedback - devices that actually move inside the cab to simulate flippers, slingshots, and bumpers.

Real pinball is a tactile experience.
The solenoids that whack the ball around are really powerful, and you can feel them shake the cabinet every time they fire.
Digitized sound effects just aren't the same.
For a more realistic virtual experience, you can put solenoids and other physical devices inside your cab that produce similar tactile effects in the virtual game.
The pinball software can trigger these feedback devices in sync with the game play.
So when a bumper fires in the simulation, you can actually feel a solenoid fire in your cab.
You can likewise add bright LEDs and strobes that flash in sync with game events.
This makes for a dramatic light show, much more interesting than just images on a TV.

The current generation of pinball software makes it fairly straightforward to attach an array of mechanical devices and external lights.
You need another I/O controller for this capability, known in this case as an "output controller".
The Pinscape Controller can handle this task, and there are several commercial options as well.
As for the feedback effects, there's a fairly standard set of lights, solenoids, and motors that most people use, but the control systems are so flexible that you hook up almost anything you can think of.

==  That sounds like a lot of work...

If you're new to the virtual cabinet world and you weren't already acquainted with all these bells (literally) and whistles, you might be feeling a little intimidated by all of this.
You might have been picturing just the basics of the Windows PC in the fancy wooden box, and you might have been thinking in terms of what you could build out of ordinary PC equipment.
But a lot of the stuff I just mentioned obviously can't be done with ordinary PC parts alone.

The good news is that everything described above is not only possible, but well understood.
It's all been reduced to recipes that you can follow.
Lots of people have built cabs with these features.
The software infrastructure that supports all of this is mature, and it's specifically designed with all these features in mind.
There's no need to "hack" anything to trick the software into doing these things; the software already knows all about backbox displays, DMDs, nudging, plungers, and feedback devices.
You just need to tell it what you have installed, and it'll take advantage of it to create a great playing experience.

Most importantly, the whole setup can be built by a committed DIYer.
That's where this guide comes in.
We'll explain how to implement all the things that go into a virtual pin cab, covering the best DIY solutions as well as the commercial product options.

By the way, "DIY" doesn't mean "poor man's", which is the way a lot of people think of it.
In fact, it's really quite the opposite these days, thanks to technologies like ubiquitous computing, 3D printing, and the relentless pace of progress in electronics.
DIY means you can build exactly what you want.
It means you don't have to settle for what some marketing department thought was good enough for the least common denominator.
Yes, you do still see forum discussions about "hacks" and cheap solutions.
That's not what this guide is about.
The approaches we'll cover in this guide are modern, no-compromises solutions.
Some of them have capabilities that you simply can't find in the commercial alternatives.

